version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    environment:
      - SYNAPSE_SERVER_NAME=domain.com
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./data:/data
    ports:
      - "8008:8008"
    restart: unless-stopped
